# This Dockerfile is generated by nestg
# https://github.com/abcdlsj/share/go/nestg
# Author: abcdlsj

FROM golang:alpine AS builder
WORKDIR /build
COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -trimpath -o pasty .

FROM alpine:latest
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /build/pasty .
CMD ["./pasty"]